name: ci-polaris 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]  
jobs:
  polaris-scan:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 또는 'zulu', 'adopt' 등 원하는 JDK 배포판 선택 가능
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: ${{ vars.APPLICATION_NAME }}
          polaris_project_name: ${{ github.event.repository.name }}
          
          ### Signature scan
          polaris_test_sca_type: "SCA-SIGNATURE"

          ### Signature scan
          coverity_config_path: ./coverity.yaml
